[package]
name = "hocon"
version = "0.3.0"
authors = ["zolkko <zolkko@gmail.com>"]
edition = "2021"

[dependencies]
nom = "7"
serde = { version = "1" }

[dev-dependencies]
serde_derive = { version = "1" }
