[package]
name = "hocon"
version = "0.3.0"
authors = ["zolkko <zolkko@gmail.com>"]
edition = "2021"
rust-version = "1.78.0"

[dependencies]
nom = "7"
nom_locate = "4"
serde = { version = "1" }

[dev-dependencies]
serde_derive = { version = "1" }
